# Basic
title: Nicky
subtitle: ä¸ªäººç«™
description: I Believe I Can. 
# å¤´åƒé‡Œé¢çš„æ ‡é¢˜
avatarTitle: Nicky
# å¤´åƒé‡Œé¢çš„æè¿°
avatarDesc: Python / å…¨æ ˆå¼€å‘
url: "http://returnpy.github.io"

# Comment
comment:
    disqus: leopard
    # gitment: xxx // éœ€è¦ä¿®æ”¹ comments.htmlä¸­çš„client_idå’Œclient_secret
    # uyan: 2143225  # æœ‰è¨€id,ç™»å½•æœ‰è¨€å®˜ç½‘ç”³è¯·

# Social
social:
    weibo: 18601011935 
    github: returnpy
    # zhihu: panpanleopard
    # juejin: xxx
    jianshu: 18601011935
    # twitter: 
    # mail: leopardpan@icloud.com


# ç™¾åº¦ç»Ÿè®¡ 
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·å»æ‰æˆ–è€…æ›´æ¢ id 
baidu:
    id: c58b1ad83a64dd64e933ae10aab48e89

# Google Analytics
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·å»æ‰æˆ–è€…æ›´æ¢ id
# ga:
#     id: xxxx  
#     host: auto  


# ã€Š----------------- ä¸Šé¢çš„ä¿¡æ¯ä¿®æ”¹æˆä½ è‡ªå·±çš„ ---------------------------ã€‹
#
#
#  _post/ ä¸‹çš„æ–‡ç« æ›´æ¢æˆä½ è‡ªå·±çš„æ–‡ç« 
#  å¸®å¿™starä¸€ä¸‹ï¼Œæ„Ÿè°¢~ğŸ˜† åœ°å€ï¼š https://github.com/returnpy/returnpy.github.io
#
#
# ã€Š--------------- ä¸‹é¢çš„ä¿¡æ¯å¯ä»¥è‡ªè¡Œé€‰æ‹©æ˜¯å¦ä¿®æ”¹ ------------------------ã€‹


permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: åšå®¢ä¸»é¡µ

# Navigation buttons in the front page.s
nav:
    - {title: æ‰€æœ‰æ–‡ç« , description: archive, url: '/archive'}   
    - {title: æ ‡ç­¾, description: tags, url: '/tags'}      
    - {title: å…³äºæˆ‘, description: ç®€å†æˆ³è¿™é‡Œ, url: '/about'}      
    - {title: å¸¸ç”¨å·¥å…·, description: ç®€å†æˆ³è¿™é‡Œ, url: '/about'}      
    

# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 10
paginate_path: "page/:num/"


